name = "LibreHouse"
babel = ["zh-N", "en-2"]

[contact]
email = "i+noc@outv.im"
telegram = "outvi"
mastodon = "@ov@social.outv.im"
github = "outloudvi"

[persona]
pgp = "7A9543829E475D7D3826B08DA725CB57CA65CAFE"
