name = "LUKK"

[contact]
email = "yingluqwq@duck.com"

[persona]
ssh = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRel1XTSrdOHK8rI3Koiq7Jfu+vbh9NNqF142a/PMWOTdAqQNGzGQNEjE1jVMI0KTVFSg6hWinpndS9jrzsn9ym5FqD5lyt/UVwIP6lPY+31O+ljIMwKtWwM/0KK0rdXqNODxshjCHiv5cTwM9ACyfBbTDMGI+lYOXJhZX5k4Sm+xfPogzBaYLXQucBMsYgfjVODDoa00lvloly8NCXVpkAaUJu1PHkzURoF3i+hXhJqXvKUEvcgb+1lyPzDswpx3ScuVJDlRZYFHvJFe856xx0gRNlrpQ+abNo+xsCBH84dWJPFFNDBstETm2x+e/HbqPnyFLtJN/qI/A663hxfkCnT4JtONK4hFbftIQwKBDjNutqvpEyljpbe+J6BEj7QfbSgJ8+3u28868rsZs7/35M9TpdT/0mYNOA3UfPThTG75PR/ntusXFd8t3lvtj/XNHI0P8ShUH8aPkaXsMFAnZEEDdhUPGfcj1tnX48Em9+92MLD4F2Sk7R9QKSk9YPFE= u0_a552@localhost"
pgp = "FE878660B4658AE0D8DBCFB00C0509BCACEAC90E"
