[Cupkappu-HK1]
asn = 4201270019
cidr = ["10.127.19.1/27"]
desc = "Cup's Hong Kong Node 1"

[Cupkappu-JP]
asn = 4201270019
cidr = ["10.127.19.2/27"]
desc = "Cup's Japan Osaka Node"

[Cupkappu-HK2]
asn = 4201270019
cidr = ["10.127.19.3/27"]
desc = "Cup's Hong Kong Node 2"
