["10.127.66.0/24"]
type = "subnet"
name = "FIXMIX-NET4-NEOA"
description = "fixmix Technologies NeoNetwork IPv4 Block"

["fd10:127:aa66::/48"]
type = "subnet"
name = "FIXMIX-NET6-NEOA"
description = "fixmix Technologies NeoNetwork IPv6 Block"
