["10.127.13.0/24"]
type = "subnet"
name = "Ndoskrnls LAN"
description = "For devices which being connected locally to Ndoskrnls Master Router"

["fd10:127:13::/48"]
type = "subnet"
name = "Ndoskrnls LAN (IPv6)"
description = "For devices which being connected locally to Ndoskrnls Master Router"
