["10.127.19.96/27"]
type = "subnet"
name = "cupkappu"
description = "Cup's neonetwork Asia"

["10.127.19.64/27"]
type = "subnet"
name = "cupkappu"
description = "Cup's neonetwork Japan"

["10.127.19.32/27"]
type = "subnet"
name = "cupkappu"
description = "Cup's neonetwork EU"

["10.127.19.0/27"]
type = "subnet"
name = "cupkappu"
description = "Cup's neonetwork Core"

